# Generated by Django 4.2.3 on 2023-08-10 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=15)),
                ('phone', models.CharField(max_length=15)),
                ('dsg', models.CharField(max_length=50)),
                ('salary', models.IntegerField()),
                ('city', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('state', models.CharField(blank=True, default='', max_length=30, null=True)),
            ],
        ),
    ]
